services:
  nginx:
    image: nginx:1.23
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
#      - static_files:/home/app/staticfiles
      - ./nginx/file/:/media/live/

#volumes:
#  static_files: